### PR TITLE
Fix locale issues in kunquat-player and kunquat-export

### PR DESCRIPTION
**Pull request by kagu**
This branch fixes issue #585.

### CODE REVIEW

**Comment by cyberixae** [comment]
Perhaps you could use Python byte string representation for problematic meta data

**Comment by kagu** [comment]
Maybe, although ignoring problematic metadata is probably safer, and it doesn't affect the core functionality of the program.

**Comment by cyberixae** [comment]
The warning could of course also tell the user "Try running kunquat-player with `LANG=en_US.UTF-8 kunquat-player`" or something similar. I personally like error messages that suggest you try some action that might fix the problem.

**Comment by kagu** [comment]
That's a good point and I'll keep that in mind when dealing with error messages in the future. But I think I'll merge this one as is.

**Pull request merged**
